
package com.idega.cxf.test.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import com.idega.cxf.test.client.HelloSpring;

/**
 * This class was generated by the CXF 2.0.1-incubator
 * Mon Aug 27 16:41:21 EEST 2007
 * Generated source version: 2.0.1-incubator
 * 
 */

@WebServiceClient(name = "HelloSpringImplService", targetNamespace = "http://service.test.cxf.idega.com/", wsdlLocation = "file:HelloSpring.wsdl")
public class HelloSpringImplService extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://service.test.cxf.idega.com/", "HelloSpringImplService");
    private final static QName HelloSpringImplPort = new QName("http://service.test.cxf.idega.com/", "HelloSpringImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:HelloSpring.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:HelloSpring.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public HelloSpringImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloSpringImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns HelloSpringImplPort
     */
    @WebEndpoint(name = "HelloSpringImplPort")
    public HelloSpring getHelloSpringImplPort() {
        return (HelloSpring)super.getPort(HelloSpringImplPort, HelloSpring.class);
    }

}
